{% set name = "jupyter-kernel-provisioner-proxy" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_kernel_provisioner_proxy-{{ version }}.tar.gz
  sha256: 44bb8482f68123e7523b06ead44e20ffc0df6cfbe157c9584e622fddab5b0613

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv
  entry_points:
    - jupyter-kernel-provisioner-proxy = jupyter_kernel_provisioner_proxy.cli:main

requirements:
  host:
    - python >=3.8,<4
    - pip
    - hatchling
  run:
    - python >=3.8,<4
    - rich-click >=1.6.1,<2
    - httpx >=0.24.1,<1
    - httpx-ws >=0.4.0,<1
    - jupyter_client
    - wsproto
    - pyzmq
    - python-dateutil

test:
  imports:
    - jupyter_kernel_provisioner_proxy
  commands:
    - pip check
  requires:
    - pip
  commands:
    - jupyter-kernel-provisioner-proxy install --help

about:
  home: https://github.com/davidbrochart/jupyter-kernel-provisioner-proxy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter kernel provisioner proxy
  dev_url: https://github.com/davidbrochart/jupyter-kernel-provisioner-proxy
  doc_url: https://github.com/davidbrochart/jupyter-kernel-provisioner-proxy

extra:
  recipe-maintainers:
    - davidbrochart
